import { createGroq } from "@ai-sdk/groq"
import { createGoogleGenerativeAI } from "@ai-sdk/google"
import type { LanguageModel } from "ai"
import type { Intent, ProviderId, Scene } from "./types"

type Tier = {
  id: Exclude<ProviderId, "offline">
  label: string
  short: string
  model: LanguageModel
}

const groq = createGroq({
  apiKey: process.env.GROQ_API_KEY,
})

const google = createGoogleGenerativeAI({
  apiKey: process.env.GOOGLE_GENERATIVE_AI_API_KEY,
})

export const PRIMARY: Tier = {
  id: "groq",
  label: "Groq · Qwen 3.6 27B",
  short: "Groq",
  model: groq("qwen/qwen3.6-27b"),
}

export const FALLBACK: Tier = {
  id: "gemini",
  label: "Google · Gemini 3.6 Flash",
  short: "Gemini",
  model: google("gemini-3.6-flash"),
}

export const PROVIDER_META: Record<
    ProviderId,
    { label: string; short: string }
> = {
  groq: {
    label: PRIMARY.label,
    short: PRIMARY.short,
  },

  gemini: {
    label: FALLBACK.label,
    short: FALLBACK.short,
  },

  offline: {
    label: "Offline grounded fallback",
    short: "Offline",
  },
}

export type ClassifyOutput = {
  intent: Intent
  confidence: number
  rationale: string
  provider: ProviderId
}

/**
 * Intent classification is deliberately local.
 *
 * This is only routing logic. It does not represent whether
 * the final answer was generated by an AI provider.
 */
export function classifyIntent(
    query: string,
    scene: Scene,
): ClassifyOutput {
  const result = heuristicIntent(query, scene)

  return {
    ...result,
    provider: "offline",
  }
}

export function heuristicIntent(
    query: string,
    scene: Scene,
): {
  intent: Intent
  confidence: number
  rationale: string
} {
  const q = query
      .toLowerCase()
      .replace(/[?.,!]/g, " ")
      .replace(/\s+/g, " ")
      .trim()

  const score: Record<Intent, number> = {
    caption: 0,
    vqa: 0,
    grounding: 0,
    change: 0,
    fusion: 0,
  }

  // -------------------------------------------------------------------------
  // CAPTION
  // -------------------------------------------------------------------------

  if (
      /(describe|description|summar|summary|overview|what is this|what does this show|caption)/.test(
          q,
      )
  ) {
    score.caption += 3
  }

  // -------------------------------------------------------------------------
  // VQA
  // -------------------------------------------------------------------------

  if (
      /(how many|count|number of|is there|are there|what color|which|does it have|dominant|how much|present)/.test(
          q,
      )
  ) {
    score.vqa += 3
  }

  // -------------------------------------------------------------------------
  // GROUNDING
  // -------------------------------------------------------------------------

  if (
      /(point to|where is|where are|locate|location of|delineate|highlight|find the|show me the|mark|identify where|which area)/.test(
          q,
      )
  ) {
    score.grounding += 3
  }

  // -------------------------------------------------------------------------
  // CHANGE
  // -------------------------------------------------------------------------

  if (
      /(chang|before|after|difference|grew|growth|expanded|expansion|flood|flooded|between the two|two dates|over time|increase|decrease|removed|new area|temporal|earlier|later)/.test(
          q,
      )
  ) {
    score.change += 3
  }

  // -------------------------------------------------------------------------
  // FUSION
  // -------------------------------------------------------------------------

  if (
      /(sar|radar|backscatter|fuse|fusion|both sensors|combine.*sensor|optical.*sar|sar.*optical|radar.*optical|optical.*radar)/.test(
          q,
      )
  ) {
    score.fusion += 3
  }

  // -------------------------------------------------------------------------
  // Object-specific hints
  // -------------------------------------------------------------------------

  if (/\bbridge\b/.test(q)) {
    if (
        /(where|locate|point|highlight|show|mark)/.test(q)
    ) {
      score.grounding += 2
    } else {
      score.vqa += 1
    }
  }

  if (
      /(ship|ships|vessel|vessels|building|buildings|road|roads|park|parks|tree|trees|water|harbor|harbour)/.test(
          q,
      )
  ) {
    score.vqa += 1
  }

  // -------------------------------------------------------------------------
  // Select supported capability
  // -------------------------------------------------------------------------

  let best: Intent = scene.availableIntents[0]
  let bestScore = -1

  for (const intent of scene.availableIntents) {
    if (score[intent] > bestScore) {
      bestScore = score[intent]
      best = intent
    }
  }

  const confidence =
      bestScore <= 0
          ? 0.55
          : Math.min(0.88, 0.55 + bestScore * 0.08)

  return {
    intent: best,
    confidence,
    rationale:
        bestScore <= 0
            ? "No strong intent signal was detected; defaulted to the primary capability available for this scene."
            : "Routed locally using deterministic question-intent matching.",
  }
}